name: project_environment
dependencies:
- python=3.8

- pip:
  - numpy
  - onnxruntime
  - joblib
  - scikit-learn
  - inference-schema[numpy-support]
  - azureml-defaults
  - azureml-core

channels:
- anaconda
- conda-forge
